[package]
name = "wio-terminal-blink-rs"
version = "0.1.0"
authors = ["tomoyuki-nakabayashi <tomo.wait.for.it.yuki@gmail.com>"]
edition = "2018"

[dependencies]
wio_terminal = "0.3.0"
panic-halt = "0.2"
